### ISSUE TITLE
Exercise content

### ISSUE THREAD

**Issue by thomastuts** [learn-co-curriculum/javascript-closures-lab#1]
Going through the lab exercises, I noticed that we're touching upon functions returning functions again - the basic stuff like the `adder()` example. Those are obviously closures too, but we cover them in the previous lessons already.

I made up an exercise where you have a counter closure that keeps track of something, illustrating the concept of modifying the variables inside a closure. Do you think that's enough for this lesson? It covers all the objectives except for 'Use a closure to define a partially applied function' which is pretty much already handled in lessons lesson 7.1 and 7.2, no?

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.

**Comment by pletcher** [comment]
@thomastuts agreed -- these lessons kind of get intentionally repetitive, as these concepts have proven difficult for students in the past and we want to give them as much practice as possible.

I like the example that you've come up with -- if it's cool with you, let's also do some form of partial function application here, just so students get as much practice as possible.
